[package]
name = "boost_scope_exit"
description = "Boost C++ library boost_scope_exit packaged using Zanbil"
version = "0.1.0"
edition = "2024"
links = "boost_scope_exit"
license = "BSL-1.0"
repository = "https://github.com/zanbilify/boost_scope_exit"

[package.metadata.zanbil]
make_dependencies_public = true

[dependencies]
boost_config = { version = "0.1.0", path = "../boost_config" }
boost_function = { version = "0.1.0", path = "../boost_function" }
boost_preprocessor = { version = "0.1.0", path = "../boost_preprocessor" }
boost_type_traits = { version = "0.1.0", path = "../boost_type_traits" }
boost_typeof = { version = "0.1.0", path = "../boost_typeof" }

[build-dependencies]
zanbil-boost-build = "0.1.0"
